server:
  port: 8888
spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.70.250.230:3306/test?useUnicode=true;characterEncoding=UTF-8;useSSL=false;serverTimezone = GMT
    #    url: jdbc:mysql://81.70.250.230:3306/park?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 17633908064

#mybatis:
#  mapper-locations: classpath:mapper/*.xml

